export enum CommonErrorCode {
  VALIDATION_ERROR = "VALIDATION_ERROR|400",
  AN_UNKNOWN_ERROR = "AN_UNKNOWN_ERROR|500",
  PATH_NOT_FOUND = "PATH_NOT_FOUND|404",
  UNAUTHORIZED = "UNAUTHORIZED|401",
  FORBIDDEN = "FORBIDDEN|403",
  GENERATE_FILE_ERROR = "GENERATE_FILE_ERROR_500|500",
}
