enum SALE_TYPE {
  CERTIFICATE = 'CERTIFICATE',
  VERIFIED = 'VERIFIED'
}

enum STATUS {
  LISTING = 'LISTING',
  PENDING = 'PENDING',
  IN_PROCESS = 'IN_PROCESS'
}

enum MATERIAL_KIND {
  PAINTING = 'PAINTING',
  WORKS_ON_PAPER = 'WORKS_ON_PAPER',
  EDITION = 'EDITION',
  SCULPTURE = 'SCULPTURE',
  DECORATIVE = 'DECORATIVE',
  MULTI_MEDIA = 'MULTI_MEDIA',
  OTHERS = 'OTHERS'
}

enum BOUGHT_PLACE {
  AUCTION_HOUSE = 'AUCTION_HOUSE',
  GALLERY = 'GALLERY',
  INDIVIDUALS_OR_DEALERS = 'INDIVIDUALS_OR_DEALERS',
  INHERITED_OR_GIFTED = 'INHERITED_OR_GIFTED',
  OTHER = 'OTHER'
}

enum PROOF_TYPE {
  CERTIFICATE_OF_AUTHENTICITY = 'CERTIFICATE_OF_AUTHENTICITY',
  GALLERY_AUCTION_GUARANTEE_PAPER = 'GALLERY_AUCTION_GUARANTEE_PAPER',
  INVOICE_AUCTION_PROFILE = 'INVOICE_AUCTION_PROFILE',
  ONLINE_TRANSACTION_RECORDS = 'ONLINE_TRANSACTION_RECORDS',
  I_DONT_HAVE_THE_PROOF_OF_THE_WORK = 'I_DONT_HAVE_THE_PROOF_OF_THE_WORK'
}

enum HANDOVER_METHOD {
  DELIVERY_BY_YOURSELF = 'DELIVERY_BY_YOURSELF',
  DELIVERY_BY_OUR_DELIVERY_PARTNER = 'DELIVERY_BY_OUR_DELIVERY_PARTNER',
  I_TAKE_CARE_OF_MY_OWN_WORK_PRESERVATION = 'I_TAKE_CARE_OF_MY_OWN_WORK_PRESERVATION'
}

export { SALE_TYPE, STATUS, MATERIAL_KIND, BOUGHT_PLACE, PROOF_TYPE, HANDOVER_METHOD };
