export enum BUSINESS_FILE_TYPE {
  BUSINESS_REGISTRATION = 'BUSINESS_REGISTRATION',
  COPY_OF_BANKBOOK = 'COPY_OF_BANKBOOK',
  SHARE_HOLDER_LIST = 'SHARE_HOLDER_LIST',
  COPY_OF_REPRESENTATIVE_IDENTITY_CARD = 'COPY_OF_REPRESENTATIVE_IDENTITY_CARD',
  COPY_CORPORATE_REGISTER = 'COPY_CORPORATE_REGISTER',
  OWNER_VERIFICATION_DOCUMENT = 'OWNER_VERIFICATION_DOCUMENT'
}
